### ISSUE TITLE
I am just lost...

### ISSUE THREAD

**Issue by Usurper-King** [marcwagner/foundry_swag_docker#3]
Hi there,

first of all: thank you for the very detailed guide. I am a absolut beginner to all of this and I managed to follow through with every single step of the guide.

I did all the steps of the preparations, setting up the host and setting up the containers. 
I have all three containers running and did configure the reverse proxy.
![Screenshot 2024-06-17 171657](https://github.com/ChefsSlaad/foundry_swag_docker/assets/173076400/ae181c77-7638-40d0-ae71-7f8a86d86e9d)
I configured everything to my knowledge within the code from the guide.

`version: "3.8"

services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin                                     # replace with your local timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - SUBDOMAINS=wiederaufbauerel.duckdns.org                              # replace with to your DuckDNS subdomain name.
      - TOKEN= -my token-
                                   # replace with your DuckDNS token here
    restart: unless-stopped

  foundry:
    container_name: foundry
    hostname: foundry
    image: direckthit/fvtt-docker:latest
    expose:
      - 30000
    volumes:
      - ~/swag-foundry/foundry     # replace with the correct path to your foundry config dir
      - ~/resources  # replace with the correct path to your resources
      - ~/swag-foundry/FoundryVTT-12.327.zip                 # replace with the correct path to your foundry-x.x.x.zip file
    restart: unless-stopped

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin                                   # replace with your timezone
      - URL=wiederaufbauerel.duckdns.org                             # replace with this to your DuckDNS hostname
      - VALIDATION=http
      - DUCKDNSTOKEN= -my token -                          # replace with your DuckDNS token here
      - EMAIL= -my email-                          # replace with your email address (optional).
    volumes:
      - ./swag:/config
    ports:
      - 8080:80
      - 443:443
    restart: unless-stopped`

`# only serve https
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

server {
        listen 443 ssl http2;
        server_name wiederaufbauerel.duckdns.org  www.wiederaufbauerel.duckdns.org ;  # add your domain name here. if you want to use both with and without www add both here.

        # make sure ssl is enabled
        include~/swag-foundry/swag/nginx/ssl.conf;

        client_max_body_size 0;
        ssl_session_cache shared:SSL:10m;
        proxy_buffering off;

        location / {
            include~/swag-foundry/swag/nginx/proxy-confs;

            resolver 127.0.0.11 valid=30s;

            set $upstream_proto http;
            set $upstream_app foundry;
            set $upstream_port 30000;
            proxy_pass $upstream_proto://$upstream_app:$upstream_port;
            } 
}`

So with all this I cannot reach the site.
![Screenshot 2024-06-17 172216](https://github.com/ChefsSlaad/foundry_swag_docker/assets/173076400/0e64661a-e177-47f1-9445-fcbaab715c7a)

Thanks in advance for every helping hand!

**Comment by ChefsSlaad** [comment]
It looks like duckdns is not getting a response from your system. there could be one of two reasons:

* duckdns does not have your ip
* the route to your foundry host is blocked.

looking a https://whatismyipaddress.com/hostname-ip
it appears that wiederaufbauerel.duckdns.org directs to a datacenter in Frankfurt am Main. It looks like:  
1. you are using a VPN 
2. your ISP is using its own NAT service ->  In this case, you could request your ISP give you a public IP address. 
3. your firewall is blocking incoming trafic -> in this case look at the steps in https://github.com/ChefsSlaad/foundry_swag_docker/tree/main?tab=readme-ov-file#test 
4. You have a second internal router -> Tis is called double NAT and it makes self hostng pretty horrible. Connect your computer directly to the router using a utp cable and try again.  

Have a look at these steps and see if it helps. Let me know :)

**Comment by ChefsSlaad** [comment]
just to let you know, I've updated the guide, fixing some of the error other users found.

**Comment by ChefsSlaad** [comment]
This issue has been closed. If you problem persists, please get in touch and I will reopen this issue
